services:
  gotrip-api:
    container_name: gotrip-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3007
    volumes:
      - ./:/usr/src/gotrip
    working_dir: /usr/src/gotrip

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  gotrip-batch:
    container_name: gotrip-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/gotrip
    working_dir: /usr/src/gotrip

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge

# gotrip-next:  loclalhost:4000 => container:3000
# gotrip-api:   loclalhost:4001 => container:3007
# gotrip-batch: loclalhost:4002 => container:3008

# docker compose up -d
# docker compose stop
# docker compose start
# docker compose restart
# docker compose stop && docker compose rm -f
